// A Cloudflare Pages `_headers` file, generated rather than written by hand.
//
// Getting this backwards is what turns a deploy into a blank page. `immutable`
// on a stable-named entry point is one the browser will not re-check, so it
// goes on importing modules from a build that no longer exists -- and because
// that is a link-time failure, the whole graph dies before a line runs.
//
// The other trap is that Cloudflare *appends* matching rules rather than
// replacing them, and the strictest value wins. A `Cache-Control` on a
// catch-all arrives alongside the one on the asset root as
// "no-cache, public, max-age=..., immutable", and no-cache wins -- silently
// throwing away the caching the content addressing exists to enable. So
// exactly one rule may set Cache-Control for any given path: the catch-all
// carries security headers only, and everything with a stable name is listed.
import { encodePath } from './util.js';

export function headersFile({
  assetRoot,
  revalidate = [],
  security = '',
  generatedBy = '@3sln/js-tools -- do not edit.',
}) {
  const out = [`# Generated by ${generatedBy}`];

  if (security.trim()) {
    out.push('/*', security.replace(/\s*$/, ''), '');
  }

  out.push(
    '# Content-addressed: the filename changes whenever the bytes do, so these are',
    '# kept forever. This is the only place immutable is true.',
    `/${assetRoot}/*`,
    '  Cache-Control: public, max-age=31536000, immutable',
  );

  if (revalidate.length) {
    out.push('', '# Everything else keeps a stable name, so it must be revalidated.');
    for (const path of revalidate) {
      out.push(`/${encodePath(String(path).replace(/^\//, ''))}`, '  Cache-Control: no-cache');
    }
  }

  return `${out.join('\n')}\n`;
}

// The header lines out of an existing `_headers`, minus any Cache-Control --
// so a project can keep hand-writing its security headers and let the build own
// caching. Reads the indented lines of the file, which is where header names
// live in the Pages format.
export function securityHeadersFrom(text) {
  return text
    .split('\n')
    .filter((l) => /^\s{2}[A-Za-z]/.test(l) && !/cache-control/i.test(l))
    .join('\n');
}
