// The wire-up script.
//
// A page needs three things before it can run an unbundled module graph: the
// import map, the entry stylesheet, and the entry module. All three are
// content-addressed, so all three change on most builds -- and a page that
// hard-codes them has to be regenerated by whoever knows the build output.
// That is a lot of coupling to hand to a Cloudflare worker rendering per-book
// HTML, or to a hand-written index.html.
//
// So the build emits one script that does all three, and the page carries a
// single tag:
//
//   <script src="/@wireup/player.js"></script>
//
// which the build rewrites to the hashed URL. In development the dev server
// serves the same URL with dev paths in it, so the page is byte-identical
// either way.
//
// It must be a *classic* script (no `type`), and it must come before any module
// script in the document: an import map has to be in place before the first
// module load is triggered. Since this script appends the entry module itself,
// everything after it is in order by construction -- the one thing that breaks
// it is another module script earlier in the head.
import { encodePath } from './util.js';

const literal = (v) => JSON.stringify(v);

export function wireupSource({ imports, css = [], module = null, name = '' }) {
  const id = literal(name || 'default');
  const lines = [];

  lines.push(`// Generated by @3sln/js-tools${name ? ` for "${name}"` : ''} -- do not edit.`);
  lines.push('(function () {');
  lines.push('  var d = document;');
  lines.push('  var head = d.head || d.documentElement;');
  // An import map is inline script content as far as CSP is concerned, even
  // created this way -- so a page served under a nonce policy would reject it.
  // Carrying the wire-up's own nonce across is what an inline map in the markup
  // would have had, and it is a no-op for a policy that does not use nonces.
  lines.push('  var me = d.currentScript;');
  lines.push('  var nonce = me && me.nonce;');
  // Two copies of the same wire-up in one document would append a second import
  // map, which is an error in browsers that accept only one.
  lines.push(`  if (d.querySelector('script[data-wireup=' + ${id} + ']')) return;`);
  lines.push('  var map = d.createElement("script");');
  lines.push('  map.type = "importmap";');
  lines.push(`  map.setAttribute("data-wireup", ${id});`);
  // Embedded as a JS object literal and stringified at load, rather than as a
  // JSON string literal inside a JS string: no double escaping, and nothing to
  // get wrong about `</script>` if this ever ends up inlined.
  lines.push(`  map.textContent = JSON.stringify(${literal({ imports })});`);
  lines.push('  if (nonce) map.nonce = nonce;');
  lines.push('  head.appendChild(map);');

  for (const href of css) {
    // Skipped when the page already links it. A server-rendered page is better
    // off carrying the <link> itself -- the preload scanner finds it before
    // this script has even run -- and this is here for the pages that do not.
    lines.push(`  if (!d.querySelector('link[rel="stylesheet"][href=' + ${literal(literal(href))} + ']')) {`);
    lines.push('    var link = d.createElement("link");');
    lines.push('    link.rel = "stylesheet";');
    lines.push(`    link.href = ${literal(href)};`);
    lines.push('    head.appendChild(link);');
    lines.push('  }');
  }

  if (module) {
    // Preload now, execute at DOMContentLoaded.
    //
    // A module script inserted into the DOM is *not* deferred -- unlike one
    // written in the markup, it runs the moment it has loaded, which can be
    // before the body exists. An app that reaches for its mount point would
    // find nothing there, intermittently, depending on how fast the network
    // was. So the fetch is started immediately with modulepreload (which
    // follows the import map, and so warms the whole unbundled graph rather
    // than just the entry) and the script itself is appended once parsing is
    // done, which is what a `<script type="module" src>` in the markup would
    // have done.
    lines.push('  var pre = d.createElement("link");');
    lines.push('  pre.rel = "modulepreload";');
    lines.push(`  pre.href = ${literal(module)};`);
    lines.push('  head.appendChild(pre);');
    lines.push('  var entry = d.createElement("script");');
    lines.push('  entry.type = "module";');
    lines.push(`  entry.src = ${literal(module)};`);
    lines.push('  var mount = function () { head.appendChild(entry); };');
    lines.push('  if (d.readyState === "loading") d.addEventListener("DOMContentLoaded", mount);');
    lines.push('  else mount();');
  }

  lines.push('})();');
  return `${lines.join('\n')}\n`;
}

// Where a page refers to a wire-up before the build has rewritten it. The same
// pattern is what the dev server answers on, which is the whole point: one URL
// in the HTML, two things serving it.
export const DEFAULT_WIREUP_PATH = '/@wireup/[name].js';

export const wireupHref = (pattern, name) =>
  pattern.replace('[name]', encodePath(name));
