// The wire-up script.
//
// A page needs three things before it can run an unbundled module graph: the
// import map, the entry stylesheet, and the entry module. All three are
// content-addressed, so all three change on most builds -- and a page that
// hard-codes them has to be regenerated by whoever knows the build output.
// That is a lot of coupling to hand to a Cloudflare worker rendering per-book
// HTML, or to a hand-written index.html.
//
// So the build emits one script that does all three, and the page carries a
// single tag:
//
//   <script src="/@wireup/player.js"></script>
//
// which the build rewrites to the hashed URL. In development the dev server
// serves the same URL with dev paths in it, so the page is byte-identical
// either way.
//
// It must be a *classic* script (no `type`), and it must come before any module
// script in the document: an import map has to be in place before the first
// module load is triggered. Since this script appends the entry module itself,
// everything after it is in order by construction -- the one thing that breaks
// it is another module script earlier in the head.
import { encodePath } from './util.js';

export function wireupSource({ imports, css = [], module = null, name = '' }) {
  const literal = (v) => JSON.stringify(v);
  const lines = [];

  lines.push(`// Generated by @3sln/js-tools${name ? ` for "${name}"` : ''} -- do not edit.`);
  lines.push('(function () {');
  lines.push('  var d = document;');
  lines.push("  var head = d.head || d.documentElement;");
  // Two copies of the same wire-up in one document would append a second import
  // map, which is an error in browsers that only accept one.
  lines.push(`  if (d.querySelector('script[data-wireup=${literal(name || 'default')}]')) return;`);
  lines.push('  var map = d.createElement("script");');
  lines.push('  map.type = "importmap";');
  lines.push(`  map.setAttribute("data-wireup", ${literal(name || 'default')});`);
  lines.push(`  map.textContent = JSON.stringify(${literal({ imports })});`);
  lines.push('  head.appendChild(map);');

  for (const href of css) {
    lines.push('  var link = d.createElement("link");');
    lines.push('  link.rel = "stylesheet";');
    lines.push(`  link.href = ${literal(href)};`);
    lines.push('  head.appendChild(link);');
  }

  if (module) {
    lines.push('  var entry = d.createElement("script");');
    lines.push('  entry.type = "module";');
    lines.push(`  entry.src = ${literal(module)};`);
    lines.push('  head.appendChild(entry);');
  }

  lines.push('})();');
  return `${lines.join('\n')}\n`;
}

// Where a page refers to a wire-up before the build has rewritten it. The same
// pattern is what the dev server answers on, which is the whole point: one URL
// in the HTML, two things serving it.
export const DEFAULT_WIREUP_PATH = '/@wireup/[name].js';

export const wireupHref = (pattern, name) =>
  pattern.replace('[name]', encodePath(name));
